paths:  
  /api/products/{pid}:
    get:
      tags:
      - Get Product by ID
      summary: Busca producto por id.
      parameters:
        - in: path
          name: pid
          required: true
          description: id referente al producto
          schema:
            type: string
            default: 665738cb7c77ef767d8954a9
      responses:
        200:
          description: Producto encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schema/Products/Product'
    put:
      tags:
      - Modify Product
      summary: Modifica un producto.
      parameters:
        - in: path
          name: pid
          required: true
          description: id de referencia al producto
          schema:
            type: string
            default: 665738cb7c77ef767d8954a9
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/parameters/schemas/Product'
        required: true
      responses:
        200:
          description: Producto modificado con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schema/Products/Product'
    delete:
      tags:
      - Delete Product
      summary: Elimina un producto.
      parameters:
        - in: path
          name: pid
          required: true
          description: id de referencia al producto
          schema:
            type: string
            default: 66d095ce6562abc873487b74
      responses:
        200:
          description: Producto eliminado con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schema/Products/Product'
  /api/products:
    post:
      tags:
      - Create Product
      summary: Registro de un producto.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/parameters/schemas/Product'
        required: true
      responses:
        200:
          description: Se registró el producto correctamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schema/Products/Product'
        500: 
          description: Error del servidor.
          content:
            application/json:
              schema:
                $ref: '#/components/schema/Products/InternalServerError'
  /api/products/getProdsApi:
    get:
      tags:
      - Get All Products
      summary: Muestra todos los productos.
      parameters:
        - in: query
          name: limit
          schema:
            type: number
            default: 10
          description: Cantidad de productos por página.
        - in: query
          name: page
          schema:
            type: number
            default: 1
          description: Número de la página para la paginación.
        - in: query
          name: sort
          schema:
            type: string
            enum: [asc, desc]
            default: asc
          description: Orden de los productos por nombre (ascendente o descendente).
        - in: query
          name: query
          schema:
            type: string
            enum: [true, false, Consola, Perifericos, Mobiliario]
            default: Consola
          description: Término de búsqueda opcional para filtrar productos, puede ser categoria o filtro true false.
      responses:
        200:
          description: Mostrando todos los productos correctamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schema/Products/GetAllProducts'
        500: 
          description: Error del servidor.
          content:
            application/json:
              schema:
                $ref: '#/components/schema/Products/InternalServerError'
